version: "3.0"
services:
  backend:
    build: ./backend
    networks:
      - mynetwork
    devices:
      - "/dev/spidev0.0:/dev/spidev0.0"
      - "/dev/spidev0.1:/dev/spidev0.1"
      - "/dev/spidev1.2:/dev/spidev1.2"
      - "/dev/gpiomem"
    privileged: true
    image: flask-app
    expose:
      - "5000"
    volumes:
      - /greengrass/v2:/greengrass/v2
      - /home/ggc_user/greengrass_data:/app/data
      - ./backend:/src
    environment:
      - AWS_REGION=eu-west-1
      - SVCUID
      - AWS_GG_NUCLEUS_DOMAIN_SOCKET_FILEPATH_FOR_COMPONENT
      - AWS_CONTAINER_AUTHORIZATION_TOKEN
      - AWS_CONTAINER_CREDENTIALS_FULL_URI
      - AWS_IOT_THING_NAME
  frontend:
    build: ./frontend
    networks:
      - mynetwork
    image: react-webapp
    ports:
      - "3000:3001"
    volumes:
      - /greengrass/v2:/greengrass/v2
      - ./frontend:/src
    environment:
      - REACT_APP_BE_HOST=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  mynetwork:
    driver: bridge
